apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-notebook
  labels:
    app: minimal-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-notebook
  template:
    metadata:
      labels:
        app: minimal-notebook
    spec:
      containers:
      - name: minimal-notebook
        image: jupyter/minimal-notebook:latest
        ports:
        - containerPort: 8888