apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: {{ingress_class}}
  labels:
    instance: {{notebook_id}}
    k8s-app: privatejupyter
  name: {{notebook_id}}
  namespace: {{namespace}}
spec:
  rules:
  - host: {{notebook_id}}.{{domain_name}}
    http:
      paths:
      - backend:
          service:
            name: {{notebook_id}}
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{notebook_id}}.{{domain_name}}
    secretName: {{notebook_id}}-tls