apiVersion: v1
kind: Pod
metadata:
  labels:
    instance: {{notebook_name}}
    k8s-app: privatejupyter
    owner: {{username}}
    time2delete: ttl-{{days}}
  name: {{notebook_name}}
  namespace: {{namespace}}
spec:
  containers:
  - name: {{notebook_name}}
    args:
    - /.run
    - /ML_platform_tests/SetupPrivateJupyterLab.sh
    env:
    - name: "JUPYTER_TOKEN"
      value: {{token}}
    {% if gpu_available and gpu_request == 0 %} 
    - name: NVIDIA_VISIBLE_DEVICES
      value: none
    {% endif %}
    image: {{image}}
    imagePullPolicy: Always
    ports:
    - containerPort: 9999
    resources:
      limits:
        cpu: {{cpu_limit}}
        memory: {{memory_limit}}
        {% if gpu_available %}
        nvidia.com/gpu: {{gpu_limit}}
        {% endif %}
      requests:
        cpu: {{cpu_request}}
        memory: {{memory_request}}
        {% if gpu_available %}
        nvidia.com/gpu: {{gpu_request}}
        {% endif %}
    volumeMounts:
    - mountPath: /data
      name: local-scratch
      readOnly: false
  restartPolicy: Always
  volumes:
  - hostPath:
      path: /data
    name: local-scratch