apiVersion: v1
kind: Service
metadata:
  labels:
    instance: {{notebook_name}}
    k8s-app: privatejupyter
  name: {{notebook_name}}
  namespace: {{namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9999
  selector:
    instance: {{notebook_name}}
  type: NodePort