apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{notebook_name}}
  labels:
    app: {{notebook_name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{notebook_name}}
  template:
    metadata:
      labels:
        app: {{notebook_name}}
    spec:
      containers:
      - name: {{notebook_name}}
        image: {{image}}
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: {{memory}}
            cpu: {{cpu}}
          limits:
            memory: {{memory}}
            cpu: {{cpu}}
        args: ["start-notebook.sh", "--NotebookApp.password='{{password_hash}}'"]