apiVersion: v1
kind: Pod
metadata:
  name: {{notebook_name}}
  namespace: {{namespace}}
  labels:
    instance: {{notebook_name}}
spec:
  containers:
  - name: {{notebook_name}}
    image: {{image}}
    ports:
    - containerPort: 8888
    resources:
      requests:
        memory: {{memory}}
        cpu: {{cpu}}
      limits:
        memory: {{memory}}
        cpu: {{cpu}}
    args: ["start-notebook.sh", "--NotebookApp.password='{{password}}'"]