apiVersion: v1
kind: Service
metadata:
  name: {{notebook_name}}
  namespace: {{namespace}}
spec:
  selector:
    instance: {{notebook_name}}
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8888